config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments

  get 'pages/info'

  resources :ideas

  root to: redirect('/ideas')

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :idea
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @idea = Idea.find(params[:id])
    @comments = @idea.comments.all
    @comment = @idea.comments.build
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.new
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :idea_id)
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @comments ||= []
    @idea = Idea.find(params[:id])
    @comments = @idea.comments.all
    @comment = @idea.comments.build
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_form.html.slim
= form_for @comment do |f|
  - if @comment.errors.any?
    #error_explanation
      h2 = "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      ul
        - @comment.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user_name
    = f.text_field :user_name
  .field
    = f.label :body
    = f.text_area :body
  .actions = f.submit 'Save'

app/views/comments/edit.html.slim
h1 Editing comment

== render 'form'

= link_to 'Show', @comment
'|
= link_to 'Back', comments_path

app/views/comments/index.html.slim
h1 Listing comments

table
  thead
    tr
      th User name
      th Body
      th Idea
      th
      th
      th

  tbody
    - @comments.each do |comment|
      tr
        td = comment.user_name
        td = comment.body
        td = comment.idea_id
        td = link_to 'Show', comment
        td = link_to 'Edit', edit_comment_path(comment)
        td = link_to 'Destroy', comment, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.slim
p
  strong User name:
  = @comment.user_name
p
  strong Body:
  = @comment.body
p
  strong Idea:
  = @comment.idea_id

= link_to 'Back', comments_path

app/views/ideas/_form.html.slim
= form_for @idea, html: { multipart: true } do |f|
  - if @idea.errors.any?
    #error_explanation
      h2 = "#{pluralize(@idea.errors.count, "error")} prohibited this idea from being saved:"
      ul
        - @idea.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :picture
    = f.file_field :picture
  .actions = f.submit 'Save'

app/views/ideas/edit.html.slim
h1 Editing idea

== render 'form'

= link_to 'Show', @idea
'|
= link_to 'Back', ideas_path

app/views/ideas/index.html.slim
h1 Listing ideas

table
  thead
    tr
      th Name
      th Description
      th Picture
      th
      th
      th

  tbody
    - @ideas.in_groups_of(3) do |group|
      .row
        - group.compact.each do |idea|
          .col-md-4
            h4
              = idea.name
            = idea.description
            = image_tag(idea.picture, width: '100%') if idea.picture?
            = link_to 'Show', idea
            = link_to 'Edit', edit_idea_path(idea)
            = link_to 'Destroy', idea, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Idea', new_idea_path

app/views/ideas/new.html.slim
h1 New idea

== render 'form'

= link_to 'Back', ideas_path

app/views/ideas/show.html.slim
.row
  .col-md-9
    = image_tag(@idea.picture_url, width: '100%') if @idea.picture.present?
  .col-md-3
    p
      strong Name:
      = @idea.name
    p
      strong Description:
      = @idea.description

    h3
      Comments
      /- @comments.to_a.each do |comment|
      - @comments.each do |comment|
        div
          strong
            = comment.user_name
          br
          p
            = comment.body
          p
            = link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }

    = render 'comments/form'

    = link_to 'Edit', edit_idea_path(@idea)
    '|
    = link_to 'Back', ideas_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Railsgirls
    link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css"
    link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap-theme.css"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav
      .container
        .navbar-header
          button.navbar-toggle data-toggle="collapse" data-target=".navbar-collapse"
            span.sr-only Toggle navigation
            - 3.times
              span.icon-bar
          a.navbar-band href="/"
            |The Idea app
        .collapse.navbar-collapse
          ul.nav.navbar-nav
            li
              = link_to 'New Idea', new_idea_path
          p.navbar-text.pull-right
            - if user_signed_in?
              |Logged in as
              = content_tag(:strong, ' ' + current_user.email)
              = image_tag current_user.gravatar_url
              = link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link'
              = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'navbar-link'
            - else
              = link_to 'Sign up', new_user_registration_path, class: 'navbar-link'
              = link_to 'Login', new_user_session_path, class: 'navbar-link'
    .container
      - if notice
        = content_tag(:p, notice, class: 'alert alert-success')
      - if alert
        = content_tag(:p, alert, class: 'alert alert-danger')
      = yield
    footer
      .container Rails Girls 2014
    script src="http://railsgirls.com/assets/bootstrap.js"

app/views/pages/info.html.slim
h1 Pages#info
p Find me in app/views/pages/info.html.slim